[package]
name = "erc6492"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
alloy = { version = "1", default-features = true }

[dependencies]
alloy = { workspace = true }

[dev-dependencies]
alloy = { workspace = true, features = [
    "node-bindings",
] }
regex = { version = "1", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "process",
    "rt-multi-thread",
] }
